stages:
  - test

default:
  tags:
    - darwin-slurm-shared

basic_test:
  id_tokens:
      SITE_ID_TOKEN:
        aud: https://gitlab.lanl.gov
  stage: test
  script: 
    - "source ./scripts/basic_ci.sh ./tests/test.py"
    
parsl_test:
  id_tokens:
      SITE_ID_TOKEN:
        aud: https://gitlab.lanl.gov
  stage: test
  script: 
    - "source ./scripts/basic_ci.sh ./tests/base.py"
    
runner_test:
  id_tokens:
      SITE_ID_TOKEN:
        aud: https://gitlab.lanl.gov
  stage: test
  script: 
    - "source ./scripts/basic_ci.sh ./example_runner.py"